[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_22"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]